kind: wasmer.io/App.v0
name: booking-app
owner: sara55m
package: sha256:a3a9ee160131782ac94cfe9cd5cbce9adc58ddb6e2176dea47060be912790a62

volumes:
  - name: booking-logs
    mount: /var/www/html/storage/logs
