kind: wasmer.io/App.v0
name: booking-app
owner: sara55m
package: sha256:37f711ec1a27a70242784e86a9df0e67ea660ef99bd157c73daff24872af898c

jobs:
  - name: migrate-database
    trigger: pre-deployment
    action:
      execute:
        command: php
        cli_args:
          - /app/artisan
          - migrate
          - --force
        timeout: 5m

  - name: clear-laravel-cache
    trigger: post-deployment
    action:
      execute:
        command: php
        cli_args:
          - /app/artisan
          - optimize:clear
        timeout: 5m

  - name: process-laravel-queue
    trigger: "* * * * *"
    action:
      execute:
        command: php
        cli_args:
          - /app/artisan
          - queue:work
          - --stop-when-empty
          - --tries=3
          - --max-time=50
        timeout: 5m

  - name: laravel-scheduler
    trigger: "* * * * *"
    action:
      execute:
        command: php
        cli_args:
          - /app/artisan
          - schedule:run
        timeout: 5m

volumes:
  - name: booking-logs
    mount: /app/storage/logs
